#!/home/binotto/.virtualenvs/googleapi_venv/bin/python3

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from datetime import datetime, time, timedelta
import pytz

# defines how to access the user's api
scopes = ['https://www.googleapis.com/auth/calendar.readonly']

# authentication of the user and fetching the creds
flow = InstalledAppFlow.from_client_secrets_file('client_secret.json', scopes)

creds = flow.run_local_server(port=0)

# create an instance of a google api client
cal = build('calendar', 'v3', credentials=creds)

# setting the time to today
tz = pytz.timezone('Europe/Berlin')
start = datetime.combine(datetime.today(), time.min).astimezone(tz)
end = start + timedelta(days=1)

# fetching the events
events = cal.events().list(calendarId='ekm7p8j@gmail.com',
                           timeMin=start.isoformat(),
                           timeMax=end.isoformat(),
                           singleEvents=True,
                           orderBy='startTime').execute()

# getting a list of events
events = events.get('items', [])

if not events:
    print("No events for today.")
else:
    for i in range(0, len(events)):
        event_start = events[i]['start'].get('dateTime', events[i]['start'].get('date'))
        event_start = datetime.fromisoformat(event_start).strftime('%I:%M %p')
        print(str(i + 1) + ". " + events[i]['summary'] + " at " + event_start)
